# Generated by Django 6.0.2 on 2026-03-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_syrups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Syrups',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Tablet', 'Tablet'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('First Aid', 'First Aid'), ('Supplement', 'Supplement')], max_length=100),
        ),
    ]
