# Generated by Django 6.0.2 on 2026-03-10 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(default=1984),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='return_policy',
            field=models.CharField(default=datetime.date(2027, 12, 31), max_length=200),
            preserve_default=False,
        ),
    ]
