# Generated by Django 6.0.2 on 2026-03-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_product_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='return_policy',
            field=models.CharField(default='Return within 7 days', max_length=200),
        ),
    ]
