# Generated by Django 6.0.2 on 2026-03-10 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_product_return_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='return_policy',
        ),
    ]
